-- Criação das tabelas base (sem dependências de outras tabelas)
CREATE TABLE REGIOES (
    ID_REGIAO INT PRIMARY KEY,
    NOME_DA_REGIAO VARCHAR(100)
);

CREATE TABLE CARGOS (
    ID_CARGO INT PRIMARY KEY,
    TITULO_DO_CARGO VARCHAR(100),
    SALARIO_MINIMO DECIMAL(10, 2),
    SALARIO_MAXIMO DECIMAL(10, 2)
);

-- Criação das tabelas com dependências lineares
CREATE TABLE PAISES (
    ID_PAIS INT PRIMARY KEY,
    NOME_DO_PAIS VARCHAR(100),
    ID_REGIAO INT,
    FOREIGN KEY (ID_REGIAO) REFERENCES REGIOES(ID_REGIAO)
);

CREATE TABLE LOCALIZACOES (
    ID_LOCALIZACAO INT PRIMARY KEY,
    ENDERECO VARCHAR(200),
    CEP VARCHAR(20),
    CIDADE VARCHAR(100),
    ESTADO_PROVINCIA VARCHAR(100),
    ID_PAIS INT,
    FOREIGN KEY (ID_PAIS) REFERENCES PAISES(ID_PAIS)
);

-- Tabela Departamentos (criada antes de Funcionários, a FK do gerente vem depois)
CREATE TABLE DEPARTAMENTOS (
    ID_DEPARTAMENTO INT PRIMARY KEY,
    NOME_DO_DEPARTAMENTO VARCHAR(100),
    ID_GERENTE INT, 
    ID_LOCALIZACAO INT,
    FOREIGN KEY (ID_LOCALIZACAO) REFERENCES LOCALIZACOES(ID_LOCALIZACAO)
);

-- Tabela Funcionários 
CREATE TABLE FUNCIONARIOS (
    ID_FUNCIONARIO INT PRIMARY KEY,
    ID_GERENTE INT,
    ID_DEPARTAMENTO INT,
    NOME VARCHAR(50),
    SOBRENOME VARCHAR(50),
    EMAIL VARCHAR(100), -- Substituído 'E-MAIL' para evitar erros de sintaxe com o hífen
    TELEFONE VARCHAR(20),
    DATA_DE_CONTRATACAO DATE,
    ID_CARGO INT,
    SALARIO DECIMAL(10, 2),
    PERCENTUAL_DE_COMISSAO DECIMAL(4, 2),
    FOREIGN KEY (ID_GERENTE) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO),
    FOREIGN KEY (ID_CARGO) REFERENCES CARGOS(ID_CARGO)
);

-- Alteração para resolver a dependência circular do ID_GERENTE
ALTER TABLE DEPARTAMENTOS
ADD CONSTRAINT FK_DEPARTAMENTO_GERENTE 
FOREIGN KEY (ID_GERENTE) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);

-- Tabela de Histórico
CREATE TABLE HISTORICO_DE_CARGOS (
    ID_FUNCIONARIO INT,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    ID_CARGO INT,
    ID_DEPARTAMENTO INT,
    PRIMARY KEY (ID_FUNCIONARIO, DATA_INICIO),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),
    FOREIGN KEY (ID_CARGO) REFERENCES CARGOS(ID_CARGO),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO)
);